// react/src/components/todo/ToDoHeader.tsx
import useAuth from "../../hooks/auth.hooks.ts";
import { TOKEN_KEY } from "../../constants/stored-token-key.ts";
import { LOGIN } from "../../constants/pages.ts";

export default function ToDoHeader() {
    const { setIsAuthenticated } = useAuth();

    function logout() {
        localStorage.removeItem(TOKEN_KEY);
        setIsAuthenticated(false);
        location.href = LOGIN;
    }

    return <div className="flex justify-between">
        <h1 className="text-4xl font-black">ToDos</h1>
        <button
            type="button"
            className="btn btn-secondary rounded-md"
            onClick={logout}
        >
            Logout
        </button>
    </div>
}

// svelte/src/components/todo/ToDoHeader.svelte
<script lang="ts">
    import { isAuth } from "../../store/auth";
    import { navigate } from "svelte-routing";
    import { LOGIN } from "../../constants/pages";
    import { TOKEN_KEY } from "../../constants/stored-token-key";

    function logout() {
        localStorage.removeItem(TOKEN_KEY);
        isAuth.set(false);
        navigate(LOGIN, { replace: true });
    }
</script>

<div class="flex justify-between">
    <h1 class="text-4xl font-black">ToDos</h1>
    <button
            type="button"
            class="btn btn-secondary rounded-md"
            on:click={logout}
    >
        Logout
    </button>
</div>
