// react/src/components/auth/AuthForm.tsx
import { ReactNode, useState } from "react";

interface AuthFromProps {
    title: string
    submitText: string
    onSubmit: (email: string, password: string) => void
    loading: boolean
    LinkElement: ReactNode,
}

export default function AuthForm({ title, submitText, loading, onSubmit, LinkElement }: AuthFromProps) {
    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")

    return <>
        <section>
            <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
                <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
                    <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
                        <h1 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
                            {title}
                        </h1>
                        <form
                            onSubmit={(e) => {
                                e.preventDefault();
                                onSubmit(email, password)
                            }}
                            className="space-y-4 md:space-y-6"
                        >
                            <div>
                                <label htmlFor="email" className="block mb-2 text-sm font-medium text-gray-900">Your
                                    email</label>
                                <input
                                    onChange={(e) => setEmail(e.target.value)}
                                    value={email}
                                    type="email"
                                    name="email"
                                    className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5"
                                    placeholder="name@company.com"
                                    required={true}
                                />
                            </div>
                            <div>
                                <label htmlFor="password"
                                       className="block mb-2 text-sm font-medium text-gray-900">Password</label>
                                <input
                                    onChange={(e) => setPassword(e.target.value)}
                                    value={password}
                                    type="password"
                                    name="password"
                                    className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5"
                                    placeholder="••••••••"
                                    required={true}
                                />
                            </div>
                            <button
                                type="submit"
                                className="btn btn-primary w-full"
                            >
                                {submitText}
                                {loading && <span className="loading loading-spinner loading-xs"></span>}
                            </button>
                            <p className="text-sm font-light text-gray-500">
                                {LinkElement}
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </>
}

// svelte/src/components/auth/AuthForm.svelte
<script lang="ts">
    export let title: string;
    export let submitText: string;
    export let onSubmit: (email: string, password: string) => void;
    export let loading: boolean;

    let email = '';
    let password = '';
</script>

<section>
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
                    {title}
                </h1>
                <form
                        on:submit|preventDefault={() => onSubmit(email, password)}
                        class="space-y-4 md:space-y-6"
                >
                    <div>
                        <label for="email" class="block mb-2 text-sm font-medium text-gray-900">Your
                            email</label>
                        <input
                                bind:value={email}
                                type="email"
                                name="email"
                                class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5"
                                placeholder="name@company.com"
                                required={true}
                        />
                    </div>
                    <div>
                        <label for="password"
                               class="block mb-2 text-sm font-medium text-gray-900">Password</label>
                        <input
                                bind:value={password}
                                type="password"
                                name="password"
                                class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5"
                                placeholder="••••••••"
                                required={true}
                        />
                    </div>
                    <button
                            type="submit"
                            class="btn btn-primary w-full"
                    >
                        {submitText}
                        {#if loading}
                            <span class="loading loading-spinner loading-xs"></span>
                        {/if}
                    </button>
                    <p class="text-sm font-light text-gray-500">
                        <slot name="link"></slot>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>
