// svelte/src/App.svelte
<script>
    import { Route, Router } from "svelte-routing";
    import Login from "./pages/Login.svelte";
    import Register from "./pages/Register.svelte";
    import ToDos from "./pages/ToDos.svelte";
    import PrivateRouteWrapper from "./lib/PrivateRouteWrapper.svelte";
    import { LOGIN, REGISTER, TODOS } from "./constants/pages";

    export let url = "";
</script>

<Router {url}>
    <Route path={LOGIN}>
        <Login/>
    </Route>
    <Route path={REGISTER}>
        <Register/>
    </Route>
    <Route path={TODOS}>
        <PrivateRouteWrapper>
            <ToDos/>
        </PrivateRouteWrapper>
    </Route>
</Router>

// react/src/App.tsx
import { BrowserRouter, Navigate, Outlet, Route, Routes } from "react-router-dom";
import Login from "./pages/Login.tsx";
import ToDos from "./pages/ToDos.tsx";
import useAuth from "./hooks/auth.hooks.ts";
import { LOGIN, REGISTER, TODOS } from "./constants/pages.ts";
import Register from "./pages/Register.tsx";

function App() {
    const {isAuthenticated} = useAuth();

    return (
        <BrowserRouter>
            <Routes>
                <Route path={LOGIN} element={<Login />} />
                <Route path={REGISTER} element={<Register />} />
                <Route element={<PrivateRoutes isAuthenticated={isAuthenticated} />}>
                    <Route path={TODOS} element={<ToDos />} />
                </Route>
            </Routes>
        </BrowserRouter>
    )
}


interface PrivateRoutesProps {
    isAuthenticated: boolean;
}

function PrivateRoutes({isAuthenticated}: PrivateRoutesProps) {
    return (
        isAuthenticated ? <Outlet /> : <Navigate to={"/"} />
    )
}

export default App
